version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: alexrashkin/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/static/
      - media:/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: alexrashkin/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static/

  gateway:
    image: alexrashkin/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static/
      - media:/media
    depends_on:
      - backend
      - frontend
      